import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Sibsutis",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning lang="en" style={{height: '100vh'}}>
            <body 
                className={`var(--bg-color) dark:bg-black ${inter.className}`} 
                style={{backgroundColor: 'var(--bg-color)'}}>
                <Providers>
                    <Header />
                        {children}
                </Providers>
            </body>
        </html>
    );
}
